### ISSUE TITLE
Turn `path` config option into array

### ISSUE THREAD

**Issue by LordMZTE** [danyspin97/wpaperd#42]
I propose an alternative configuration value for `path`. The value should also accept an array of paths, which are treated like files in a directory. For example, I might want to have wpaperd select a background randomly from one of multiple directories like this:
```toml
[default]
path = ["/usr/share/backgrounds/", "/home/lordmzte/.local/share/backgrounds/"]
```
