### ISSUE TITLE
Can't go to previous wallpaper if sorting is set to random

### ISSUE THREAD

**Issue by Rolv-Apneseth** [danyspin97/wpaperd#60]
Hi again.

I saw the AUR package had been disowned by the previous maintainer so I decided to adopt it. I went to try out `wpaperd` again (great progress btw, it's very clean now), but found that the `previous` option doesn't work when I have sorting set to `random`. Both `ascending` and `descending` work, so it's just with `random`. There's no error either, it just silently does nothing.

I'm the one who originally added that previous wallpaper functionality, but I see you've made some nice improvements! If you want I could look into what's causing the issue, just wanted to confirm if other people are having it too or it's something weird with my setup.
 
 This is my current config:
 
 ```toml
 [default]
path = "/home/rolv/repos/Wallpapers/main/"
duration = "30m"
sorting = "random"
transition_time = 400
queue_size = 20
```
