### ISSUE TITLE
Using random sort triggers unreachable! call

### ISSUE THREAD

**Issue by pjones** [danyspin97/wpaperd#96]
The following configuration triggers a call to `unreachable!` with the new group checking code:

```toml
["Dell Inc. DELL U2419H GY1VSS2"]
path = "/home/pjones/documents/pictures/backgrounds/primary"

[any]
path = "/home/pjones/documents/pictures/backgrounds/secondary"

[default]
duration = "1h"
mode = "center"
queue-size = 10
sorting = "random"
transition-time = 600

[eDP-1]
path = "/home/pjones/documents/pictures/backgrounds/primary"
```

It looks like the group checking code assumes it only applies to `Sorting::GroupedRandom` but any sorting value will trigger the group check.  I suspect the group accumulation code needs to adjust the `filter_map` closure so it only includes configuration values that are using grouped random.
